import { theme } from '../components/Theme';

const styles = {
  navContainer: {
    display: 'flex',
    justifyContent: 'center',
    width: '100%',
    height: '6rem',
    backgroundColor: theme.palette.primary.white,
  },
  nav: {
    display: 'flex',
    justifyContent: 'space-between',
  },
  logoContainer: {
    flex: 1,
    flexGrow: 1,
    display: 'flex',
    justifyContent: 'start',
    alignItems: 'center',
    cursor: 'pointer',
  },
  logo: {
    fontSize: '2rem',
    fontWeight: '700',
    color: theme.palette.primary.black,
  },

  navLinkContainer: {
    flex: 3,
    display: 'flex',
    justifyContent: 'end',
    alignItems: 'center',
    fontSize: '1.5rem',
  },
  navLink: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    color: theme.palette.primary.black,
    margin: '0 1rem',
    padding: '1rem',
    fontWeight: '700',
    cursor: 'pointer',
    textDecoration: 'none',
    '&:hover': {
      color: theme.palette.primary.main,
    },
  },
  profileContainer: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    margin: '0 1rem',
  },
  profile: {
    border: 'none',
    borderRadius: 50,
    width: '4rem',
    height: '4rem',
    cursor: 'pointer',
  },

  //   FOOTER
  newsletterContainer: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: `${theme.palette.primary.purple}`,
    width: '100%',
    height: '7rem',
    padding: '0 10rem',
    margin: '2rem 0',
  },
  newsletterTitleContainer: {
    display: 'flex',
    flexDirection: 'column',
    background: 'transparent',
    margin: 0,
  },
  newsletterTitle: {
    fontSize: '1.2rem',
    fontWeight: '700',
    color: `${theme.palette.primary.darkGray}`,
  },
  newsletterDescription: {
    fontSize: '.9rem',
    fontWeight: '400',
    color: `${theme.palette.primary.darkGray}`,
  },
  newsletter: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    height: '3.5rem',
    background: 'transparent',
    width: '50%',
    borderRadius: 10,
    backgroundColor: `${theme.palette.primary.white}`,
  },
  newsletterForm: {
    width: '100%',
    backgroundColor: 'transparent',
    margin: '0 3rem',
  },
  newsletterInput: {
    backgroundColor: 'transparent',
    borderRadius: 10,
    fontSize: '1.2rem',
    fontWeight: '400',
    width: '100%',
    height: '3.5rem',
    margin: '0 0 0 -1rem',
    color: theme.palette.primary.main,
    '& ::placeholder': {
      color: theme.palette.primary.main,
      fontWeight: '400',
    },
  },
  newsletterSubscribeButton: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: theme.palette.primary.main,
    color: theme.palette.primary.white,
    width: '3.5rem',
    height: '3.5rem',
    borderRadius: 50,
    padding: '.9rem',
    cursor: 'pointer',
    zIndex: 1000,
    '&:hover': {
      backgroundColor: theme.palette.primary.rhythm,
    },
  },
  footerContainer: {
    display: 'flex',
    justifyContent: 'space-around',
    alignItems: 'start',
    margin: '5rem 0',
  },
  footerLogoContainer: {
    flex: 1.5,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'start',
    justifyContent: 'start',
    margin: '0 1rem',
  },
  footerLogo: {
    fontSize: '3rem',
    fontWeight: '700',
    color: theme.palette.primary.main,
  },
  footerDescription: {
    textAlign: 'left',
    fontSize: '.9rem',
    fontWeight: '400',
    margin: '1rem 2rem',
  },
  socialLinksContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'start',
    justifyContent: 'start',
  },
  socialLinksTitle: {
    textAlign: 'left',
    margin: '2rem 0 0 0',
    color: theme.palette.primary.chineseBlack,
  },
  socialLinks: {
    display: 'flex',
  },
  social: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    margin: '1rem .5rem 1rem 0',
    width: '2rem',
    height: '2rem',
    borderRadius: 50,
    backgroundColor: theme.palette.primary.plumpPurple,
    cursor: 'pointer',
    '&:hover': {
      color: theme.palette.primary.white,
    },
  },
  mobileStoreContainer: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    margin: '1rem 2rem',
    cursor: 'pointer',
  },
  mobileStore: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: theme.palette.primary.purple,
    margin: '0 .5rem 0 0',
    padding: '.8rem',
    borderRadius: 1.5,
    '&:hover': {
      backgroundColor: theme.palette.primary.soap,
    },
  },
  mobileStoreIcon: {
    width: '1.2rem',
    height: '1.2rem',
    margin: '0 .5rem',
    cursor: 'pointer',
  },
  mobileStoreText: {
    color: theme.palette.primary.darkGray,
    margin: '0 .5rem',
    fontSize: '.9rem',
    fontWeight: '600',
  },
  footerLinkContainer: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'start',
  },
  footerLinkTitle: {
    margin: '0 0 .5rem 0',
    color: theme.palette.primary.chineseBlack,
  },
  footerLink: {
    color: theme.palette.primary.rhythm,
    margin: '.5rem 0',
    fontSize: '.9rem',
    cursor: 'pointer',
    textDecoration: 'none',
    '&:hover': {
      textDecoration: 'underline',
    },
  },
  copyrightContainer: {
    display: 'flex',
    justifyContent: 'center',
    width: '100%',
    margin: '0 0 1rem',
  },
  copyright: {
    width: '80%',
    fontSize: '.9rem',
  },
  //   CREATE POST
  searchContainer: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    height: '3.5rem',
    background: 'transparent',
    width: '50%',
    borderRadius: 10,
    border: `1px solid ${theme.palette.primary.ash}`,
    backgroundColor: `${theme.palette.primary.white}`,
    margin: '-1.5rem 0 0 4rem',
  },
  searchForm: {
    display: 'flex',
    width: '100%',
    backgroundColor: 'transparent',
    margin: '0 2rem',
  },
  searchInputContainer: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'start',
    height: '2rem',
  },
  searchTitle: {
    color: theme.palette.primary.chineseBlack,
    fontSize: '.8rem',
    margin: '.3rem 0 0 .5rem',
  },
  searchInput: {
    backgroundColor: 'transparent',
    borderRadius: 10,
    fontSize: '.8rem',
    fontWeight: '400',
    width: '100%',
    height: '3.5rem',
    margin: '0',
    padding: '0 .5rem',
    color: theme.palette.primary.main,
    '& ::placeholder': {
      color: theme.palette.primary.black,
      fontSize: '.8rem',
      fontWeight: '400',
    },
  },
  searchButton: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: theme.palette.primary.main,
    color: theme.palette.primary.white,
    width: '2.8rem',
    height: '2.8rem',
    borderRadius: 50,
    padding: '.5rem',
    margin: '0 2.5rem 0 0',
    cursor: 'pointer',
    zIndex: 1000,
    '&:hover': {
      backgroundColor: theme.palette.primary.rhythm,
    },
  },
  searchDivider: {
    height: '1.5rem',
    width: '1px',
    justifyContent: 'center',
    alignItems: 'center',
    margin: '3px 1rem 0 0',
    backgroundColor: theme.palette.primary.darkAsh,
  },
  createPostContainer: {
    display: 'flex',
    flexDirection: 'column',
  },
  cpTitle: {
    textAlign: 'left',
    fontSize: '2rem',
    fontWeight: 700,
  },
  cpEmphasis: {
    margin: '0 0',
    fontSize: '2rem',
    fontWeight: 700,
    color: theme.palette.primary.main,
  },
  cpPost: {
    width: '100%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    margin: '1rem 0',
  },
  buttonContainer: {
    margin: '0 0 4rem 0',
  },
  button: {
    backgroundColor: theme.palette.primary.main,
    borderRadius: 10,
    margin: '2rem 2rem 0',
    padding: '0 1.5rem',
    height: '3rem',
    width: '10rem',
    color: theme.palette.primary.white,
    fontSize: '1.2rem',
    textTransform: 'capitalize',
    '&:hover': {
      backgroundColor: theme.palette.primary.rhythm,
    },
  },
  locationField: {
    margin: '2rem 2rem 1rem',
    width: '50%',
    '& .MuiOutlinedInput-notchedOutline': {
      border: `3px solid ${theme.palette.primary.ash}`,
      borderRadius: 3,
    },
    '& .MuiInputLabel-root': {
      color: theme.palette.primary.darkAsh,
    },
  },
  mapButton: {
    margin: '2.7rem 0 0 -10rem',
    textTransform: 'initial',
    width: '7rem',
    height: '2rem',
    backgroundColor: theme.palette.primary.lightGray,
    color: theme.palette.primary.darkAsh,
    fontWeight: '600',
    borderRadius: 3,
    '&:hover': {
      backgroundColor: theme.palette.primary.lightAsh,
      color: theme.palette.primary.chineseBlack,
    },
  },
  cpRating: {
    margin: '2rem 2rem 1rem',
    padding: '.2rem 0 .2rem 1rem',
    width: '50%',
    border: `3px solid ${theme.palette.primary.ash}`,
    borderRadius: 3,
    color: theme.palette.primary.main,
    '& .MuiRating-icon': {
      fontSize: '2.75rem',
    },
  },
  cpInputContainer: {},
  amenitiesContainer: {
    width: '100%',
    display: 'flex',
    padding: '2rem 0 2rem 2rem',
  },
  amenities: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: '20rem',
    height: '6rem',
    margin: '1rem 0 2rem',
    padding: '1rem',
    fontWeight: '600',
    backgroundColor: theme.palette.primary.lightAsh,
    borderRadius: 2,
    '&:hover': {
      backgroundColor: theme.palette.primary.ash,
    },
  },
  radioContainer: {
    margin: ' 1rem 2rem',
  },
  cpGenderRadio: {
    '& .MuiSvgIcon-root': {
      color: theme.palette.primary.main,
      display: 'none',
      width: '2rem',
      height: '2rem',
    },
  },
  cpsRadioLabel: {
    margin: ' 1rem 10rem 1rem 1rem ',
  },
  genderContainer: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    margin: '.6rem -1rem 0 0',
    padding: '.1rem',
    border: `3px solid ${theme.palette.primary.main}`,
    borderRadius: 3,
    width: '2.5rem',
    height: '2.5rem',
    cursor: 'pointer',
  },
  genderChild: {
    borderRadius: 2,
    width: '2rem',
    height: '2rem',
    cursor: 'pointer',
  },
};

export { styles };
